import { Stats } from './Stats';

export interface EntityTemplate {
  type: string;
  baseStats: Partial<Stats>;
  minLevel: number;
  maxLevel: number;
}

export const enemyTemplates: EntityTemplate[] = [
  {
    type: 'Snake',
    baseStats: {
      hp: 5,
      maxHp: 5,
      mana: 0,
      maxMana: 0,
      armor: 1,
      evasion: 10,
      damage: 2,
      attackSpeed: 1.1,
      critMultiplier: 1.2,
      critChance: 3,
      poisonDamage: 1,
      poisonChance: 20,
    },
    minLevel: 1,
    maxLevel: 8,
  },
  {
    type: 'Goblin',
    baseStats: {
      hp: 8,
      maxHp: 8,
      mana: 5,
      maxMana: 5,
      armor: 2,
      evasion: 3,
      damage: 3,
      attackSpeed: 1,
      critMultiplier: 1.5,
      critChance: 5,
      extraDropChance: 5,
    },
    minLevel: 1,
    maxLevel: 10,
  },
  {
    type: 'Wolf',
    baseStats: {
      hp: 9,
      maxHp: 9,
      mana: 0,
      maxMana: 0,
      armor: 1,
      evasion: 6,
      damage: 4,
      attackSpeed: 1.3,
      critMultiplier: 1.6,
      critChance: 7,
    },
    minLevel: 2,
    maxLevel: 11,
  },
  {
    type: 'Skeleton',
    baseStats: {
      hp: 10,
      maxHp: 10,
      mana: 0,
      maxMana: 0,
      armor: 3,
      evasion: 2,
      damage: 4,
      attackSpeed: 0.9,
      critMultiplier: 1.3,
      critChance: 4,
    },
    minLevel: 1,
    maxLevel: 12,
  },
  {
    type: 'Orc',
    baseStats: {
      hp: 15,
      maxHp: 15,
      mana: 0,
      maxMana: 0,
      armor: 3,
      evasion: 1,
      damage: 5,
      attackSpeed: 1,
      critMultiplier: 1.6,
      critChance: 6,
    },
    minLevel: 5,
    maxLevel: 15,
  },
  {
    type: 'Living Armor',
    baseStats: {
      hp: 18,
      maxHp: 18,
      mana: 0,
      maxMana: 0,
      armor: 6,
      evasion: 0,
      damage: 4,
      attackSpeed: 0.8,
      critMultiplier: 1.2,
      critChance: 3,
    },
    minLevel: 6,
    maxLevel: 16,
  },
  {
    type: 'Skeleton Warrior',
    baseStats: {
      hp: 7,
      maxHp: 7,
      mana: 10,
      maxMana: 10,
      armor: 1,
      evasion: 5,
      damage: 6,
      attackSpeed: 1.2,
      critMultiplier: 1.8,
      critChance: 8,
    },
    minLevel: 7,
    maxLevel: 18,
  },
  {
    type: 'Dark Elf Scout',
    baseStats: {
      hp: 9,
      maxHp: 9,
      mana: 12,
      maxMana: 12,
      armor: 2,
      evasion: 9,
      damage: 5,
      attackSpeed: 1.3,
      critMultiplier: 1.9,
      critChance: 10,
    },
    minLevel: 8,
    maxLevel: 19,
  },
  {
    type: 'Orc Warrior',
    baseStats: {
      hp: 20,
      maxHp: 20,
      mana: 0,
      maxMana: 0,
      armor: 5,
      evasion: 0,
      damage: 7,
      attackSpeed: 0.9,
      critMultiplier: 1.7,
      critChance: 7,
    },
    minLevel: 9,
    maxLevel: 20,
  },
  {
    type: 'Harpy',
    baseStats: {
      hp: 12,
      maxHp: 12,
      mana: 15,
      maxMana: 15,
      armor: 1,
      evasion: 11,
      damage: 6,
      attackSpeed: 1.4,
      critMultiplier: 1.8,
      critChance: 9,
    },
    minLevel: 10,
    maxLevel: 21,
  },
  {
    type: 'Ghoul',
    baseStats: {
      hp: 18,
      maxHp: 18,
      mana: 5,
      maxMana: 5,
      armor: 2,
      evasion: 3,
      damage: 6,
      attackSpeed: 1.1,
      critMultiplier: 1.5,
      critChance: 5,
      poisonDamage: 2,
      poisonChance: 15,
    },
    minLevel: 11,
    maxLevel: 22,
  },
  {
    type: 'Minotaur',
    baseStats: {
      hp: 25,
      maxHp: 25,
      mana: 0,
      maxMana: 0,
      armor: 4,
      evasion: 1,
      damage: 8,
      attackSpeed: 0.8,
      critMultiplier: 2.0,
      critChance: 8,
    },
    minLevel: 12,
    maxLevel: 23,
  },
  {
    type: 'Orc Shaman',
    baseStats: {
      hp: 15,
      maxHp: 15,
      mana: 20,
      maxMana: 20,
      armor: 2,
      evasion: 2,
      damage: 5,
      attackSpeed: 0.8,
      critMultiplier: 1.9,
      critChance: 6,
      fireDamage: 3,
      fireChance: 20,
    },
    minLevel: 13,
    maxLevel: 24,
  },
  {
    type: 'Werewolf',
    baseStats: {
      hp: 22,
      maxHp: 22,
      mana: 5,
      maxMana: 5,
      armor: 3,
      evasion: 7,
      damage: 9,
      attackSpeed: 1.2,
      critMultiplier: 2.1,
      critChance: 11,
    },
    minLevel: 14,
    maxLevel: 25,
  },
  {
    type: 'Troll',
    baseStats: {
      hp: 30,
      maxHp: 30,
      mana: 5,
      maxMana: 5,
      armor: 4,
      evasion: 0,
      damage: 8,
      attackSpeed: 0.7,
      critMultiplier: 1.8,
      critChance: 5,
    },
    minLevel: 15,
    maxLevel: 26,
  },
  {
    type: 'Golem',
    baseStats: {
      hp: 35,
      maxHp: 35,
      mana: 0,
      maxMana: 0,
      armor: 8,
      evasion: 0,
      damage: 7,
      attackSpeed: 0.6,
      critMultiplier: 1.5,
      critChance: 3,
    },
    minLevel: 16,
    maxLevel: 27,
  },
  {
    type: 'Vampire',
    baseStats: {
      hp: 25,
      maxHp: 25,
      mana: 15,
      maxMana: 15,
      armor: 4,
      evasion: 8,
      damage: 7,
      attackSpeed: 1.1,
      critMultiplier: 2.0,
      critChance: 10,
      voidDamage: 3,
      voidChance: 20,
    },
    minLevel: 17,
    maxLevel: 28,
  },
  {
    type: 'Chimera',
    baseStats: {
      hp: 28,
      maxHp: 28,
      mana: 10,
      maxMana: 10,
      armor: 5,
      evasion: 6,
      damage: 10,
      attackSpeed: 1.0,
      critMultiplier: 2.2,
      critChance: 12,
      fireDamage: 4,
      fireChance: 25,
    },
    minLevel: 18,
    maxLevel: 29,
  },
  {
    type: 'Orc Warlord',
    baseStats: {
      hp: 35,
      maxHp: 35,
      mana: 10,
      maxMana: 10,
      armor: 7,
      evasion: 2,
      damage: 10,
      attackSpeed: 1,
      critMultiplier: 2.1,
      critChance: 8,
    },
    minLevel: 19,
    maxLevel: 30,
  },
  {
    type: 'Manticore',
    baseStats: {
      hp: 32,
      maxHp: 32,
      mana: 15,
      maxMana: 15,
      armor: 6,
      evasion: 7,
      damage: 11,
      attackSpeed: 1.1,
      critMultiplier: 2.3,
      critChance: 13,
      poisonDamage: 3,
      poisonChance: 20,
    },
    minLevel: 20,
    maxLevel: 31,
  },
  {
    type: 'Wraith',
    baseStats: {
      hp: 22,
      maxHp: 22,
      mana: 25,
      maxMana: 25,
      armor: 3,
      evasion: 10,
      damage: 9,
      attackSpeed: 1.2,
      critMultiplier: 2.2,
      critChance: 11,
      coldDamage: 4,
      coldChance: 25,
    },
    minLevel: 21,
    maxLevel: 32,
  },
  {
    type: 'Basilisk',
    baseStats: {
      hp: 38,
      maxHp: 38,
      mana: 20,
      maxMana: 20,
      armor: 9,
      evasion: 2,
      damage: 8,
      attackSpeed: 0.7,
      critMultiplier: 1.7,
      critChance: 6,
      poisonDamage: 5,
      poisonChance: 30,
    },
    minLevel: 22,
    maxLevel: 33,
  },
  {
    type: 'Ogre',
    baseStats: {
      hp: 40,
      maxHp: 40,
      mana: 5,
      maxMana: 5,
      armor: 6,
      evasion: 0,
      damage: 12,
      attackSpeed: 0.6,
      critMultiplier: 1.9,
      critChance: 7,
    },
    minLevel: 23,
    maxLevel: 34,
  },
  {
    type: 'Necromancer',
    baseStats: {
      hp: 25,
      maxHp: 25,
      mana: 40,
      maxMana: 40,
      armor: 3,
      evasion: 5,
      damage: 7,
      attackSpeed: 0.9,
      critMultiplier: 2.0,
      critChance: 9,
      voidDamage: 5,
      voidChance: 30,
    },
    minLevel: 24,
    maxLevel: 35,
  },
  {
    type: 'Vampire Lord',
    baseStats: {
      hp: 35,
      maxHp: 35,
      mana: 30,
      maxMana: 30,
      armor: 5,
      evasion: 9,
      damage: 11,
      attackSpeed: 1.2,
      critMultiplier: 2.3,
      critChance: 12,
      voidDamage: 5,
      voidChance: 30,
    },
    minLevel: 25,
    maxLevel: 36,
  },
  {
    type: 'Frost Giant',
    baseStats: {
      hp: 45,
      maxHp: 45,
      mana: 15,
      maxMana: 15,
      armor: 8,
      evasion: 1,
      damage: 13,
      attackSpeed: 0.7,
      critMultiplier: 2.1,
      critChance: 8,
      coldDamage: 6,
      coldChance: 35,
    },
    minLevel: 26,
    maxLevel: 37,
  },
  {
    type: 'Lich',
    baseStats: {
      hp: 30,
      maxHp: 30,
      mana: 50,
      maxMana: 50,
      armor: 4,
      evasion: 5,
      damage: 10,
      attackSpeed: 0.9,
      critMultiplier: 2.4,
      critChance: 13,
      coldDamage: 6,
      coldChance: 35,
      voidDamage: 6,
      voidChance: 35,
    },
    minLevel: 27,
    maxLevel: 38,
  },
  {
    type: 'Hydra',
    baseStats: {
      hp: 50,
      maxHp: 50,
      mana: 20,
      maxMana: 20,
      armor: 7,
      evasion: 3,
      damage: 14,
      attackSpeed: 1.3,
      critMultiplier: 2.2,
      critChance: 10,
      poisonDamage: 4,
      poisonChance: 25,
    },
    minLevel: 28,
    maxLevel: 39,
  },
  {
    type: 'Shadow Dragon',
    baseStats: {
      hp: 55,
      maxHp: 55,
      mana: 35,
      maxMana: 35,
      armor: 9,
      evasion: 6,
      damage: 15,
      attackSpeed: 1.0,
      critMultiplier: 2.5,
      critChance: 14,
      voidDamage: 7,
      voidChance: 40,
    },
    minLevel: 29,
    maxLevel: 40,
  },
  {
    type: 'Demon',
    baseStats: {
      hp: 45,
      maxHp: 45,
      mana: 35,
      maxMana: 35,
      armor: 8,
      evasion: 7,
      damage: 14,
      attackSpeed: 1.1,
      critMultiplier: 2.5,
      critChance: 14,
      fireDamage: 7,
      fireChance: 40,
    },
    minLevel: 30,
    maxLevel: 40,
  },
  {
    type: 'Behemoth',
    baseStats: {
      hp: 70,
      maxHp: 70,
      mana: 10,
      maxMana: 10,
      armor: 12,
      evasion: 0,
      damage: 16,
      attackSpeed: 0.6,
      critMultiplier: 2.0,
      critChance: 8,
    },
    minLevel: 31,
    maxLevel: 40,
  },
  {
    type: 'Archmage',
    baseStats: {
      hp: 35,
      maxHp: 35,
      mana: 60,
      maxMana: 60,
      armor: 5,
      evasion: 8,
      damage: 12,
      attackSpeed: 0.9,
      critMultiplier: 2.6,
      critChance: 15,
      fireDamage: 8,
      fireChance: 35,
      coldDamage: 8,
      coldChance: 35,
      lightDamage: 8,
      lightChance: 35,
    },
    minLevel: 32,
    maxLevel: 40,
  },
  {
    type: 'Eldritch Horror',
    baseStats: {
      hp: 60,
      maxHp: 60,
      mana: 50,
      maxMana: 50,
      armor: 10,
      evasion: 10,
      damage: 18,
      attackSpeed: 1.0,
      critMultiplier: 2.8,
      critChance: 16,
      voidDamage: 10,
      voidChance: 50,
      poisonDamage: 6,
      poisonChance: 30,
    },
    minLevel: 33,
    maxLevel: 40,
  },
  {
    type: 'Phoenix',
    baseStats: {
      hp: 55,
      maxHp: 55,
      mana: 45,
      maxMana: 45,
      armor: 7,
      evasion: 12,
      damage: 16,
      attackSpeed: 1.2,
      critMultiplier: 2.4,
      critChance: 13,
      fireDamage: 12,
      fireChance: 60,
    },
    minLevel: 34,
    maxLevel: 40,
  },
  {
    type: 'Ancient Treant',
    baseStats: {
      hp: 80,
      maxHp: 80,
      mana: 30,
      maxMana: 30,
      armor: 15,
      evasion: 0,
      damage: 14,
      attackSpeed: 0.5,
      critMultiplier: 1.8,
      critChance: 7,
      poisonDamage: 5,
      poisonChance: 40,
    },
    minLevel: 35,
    maxLevel: 40,
  },
  {
    type: 'Kraken',
    baseStats: {
      hp: 75,
      maxHp: 75,
      mana: 40,
      maxMana: 40,
      armor: 11,
      evasion: 3,
      damage: 20,
      attackSpeed: 0.8,
      critMultiplier: 2.3,
      critChance: 11,
      coldDamage: 8,
      coldChance: 45,
    },
    minLevel: 36,
    maxLevel: 40,
  },
  {
    type: 'Arch Demon',
    baseStats: {
      hp: 65,
      maxHp: 65,
      mana: 55,
      maxMana: 55,
      armor: 13,
      evasion: 9,
      damage: 19,
      attackSpeed: 1.1,
      critMultiplier: 2.7,
      critChance: 15,
      fireDamage: 10,
      fireChance: 50,
      voidDamage: 10,
      voidChance: 50,
    },
    minLevel: 37,
    maxLevel: 40,
  },
  {
    type: 'Elder Dragon',
    baseStats: {
      hp: 85,
      maxHp: 85,
      mana: 60,
      maxMana: 60,
      armor: 16,
      evasion: 7,
      damage: 22,
      attackSpeed: 0.9,
      critMultiplier: 2.8,
      critChance: 16,
      fireDamage: 12,
      fireChance: 55,
    },
    minLevel: 38,
    maxLevel: 40,
  },
  {
    type: 'Cosmic Entity',
    baseStats: {
      hp: 70,
      maxHp: 70,
      mana: 70,
      maxMana: 70,
      armor: 14,
      evasion: 14,
      damage: 20,
      attackSpeed: 1.0,
      critMultiplier: 3.0,
      critChance: 18,
      voidDamage: 15,
      voidChance: 60,
      lightDamage: 15,
      lightChance: 60,
    },
    minLevel: 39,
    maxLevel: 40,
  },
  {
    type: 'Primordial Titan',
    baseStats: {
      hp: 100,
      maxHp: 100,
      mana: 50,
      maxMana: 50,
      armor: 18,
      evasion: 5,
      damage: 25,
      attackSpeed: 0.7,
      critMultiplier: 2.6,
      critChance: 12,
      fireDamage: 10,
      fireChance: 40,
      coldDamage: 10,
      coldChance: 40,
      lightDamage: 10,
      lightChance: 40,
    },
    minLevel: 40,
    maxLevel: 40,
  },
];
